"""create table picture, product and category

Revision ID: c1df656e3140
Revises: 20a83253e933
Create Date: 2023-03-25 22:54:08.840488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1df656e3140'
down_revision = '20a83253e933'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
