"""add orders

Revision ID: ec5b793e80c8
Revises: 
Create Date: 2023-04-07 20:33:50.777646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5b793e80c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('check', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('paid', 'active', 'expired', name='statusorder'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_constraint('picture_products_tg_file_id_key', 'picture_products', type_='unique')
    op.drop_column('picture_products', 'tg_file_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picture_products', sa.Column('tg_file_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('picture_products_tg_file_id_key', 'picture_products', ['tg_file_id'])
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
